@file:Suppress("unused")

package gh.marad.tiler.os.internal.winapi

import com.sun.jna.platform.win32.WinDef

const val EVENT_MIN = 1
const val EVENT_MAX = 2147483647

val EVENT_SYSTEM_FOREGROUND = WinDef.DWORD(0x0003)
val EVENT_SYSTEM_CAPTURESTART = WinDef.DWORD(0x0008)
val EVENT_SYSTEM_CAPTURESEND = WinDef.DWORD(0x0009)
val EVENT_OBJECT_CREATE = WinDef.DWORD(0x8000)
val EVENT_OBJECT_DESTROY = WinDef.DWORD(0x8001)
val EVENT_OBJECT_SHOW = WinDef.DWORD(0x8002)
val EVENT_OBJECT_HIDE = WinDef.DWORD(0x8003)
val EVENT_OBJECT_REORDER = WinDef.DWORD(0x8004)
val EVENT_OBJECT_FOCUS = WinDef.DWORD(0x8005)
val EVENT_OBJECT_SELECTION = WinDef.DWORD(0x8006)
val EVENT_SYSTEM_CAPTUREEND = WinDef.DWORD(0x0009)
val EVENT_OBJECT_STATECHANGE = WinDef.DWORD(0x800A)
val EVENT_OBJECT_LOCATIONCHANGE = WinDef.DWORD(0x800B)
val EVENT_OBJECT_NAMECHANGE = WinDef.DWORD(0x800C)
val EVENT_OBJECT_INVOKED = WinDef.DWORD(0x8013)
val EVENT_OBJECT_CLOAKED = WinDef.DWORD(0x8017)
val EVENT_OBJECT_UNCLOAKED = WinDef.DWORD(0x8018)
val EVENT_SYSTEM_DESKTOPSWITCH = WinDef.DWORD(0x020)
val EVENT_SYSTEM_MOVESIZEEND = WinDef.DWORD(0x000B)
val EVENT_SYSTEM_MOVESIZESTART = WinDef.DWORD(0x000A)
val EVENT_SYSTEM_SWITCHSTART = WinDef.DWORD(0x0014)
val EVENT_SYSTEM_SWITCHEND = WinDef.DWORD(0x0015)
val EVENT_SYSTEM_MINIMIZESTART = WinDef.DWORD(0x0016)
val EVENT_SYSTEM_MINIMIZEEND = WinDef.DWORD(0x0017)
val EVENT_OBJECT_DRAGSTART = WinDef.DWORD(0x8021)
val EVENT_OBJECT_DRAGCANCEL = WinDef.DWORD(0x8022)
val EVENT_OBJECT_DRAGCOMPLETE = WinDef.DWORD(0x8023)
val EVENT_OBJECT_DRAGDROPPED = WinDef.DWORD(0x8026)
val EVENT_OBJECT_PARENTCHANGE = WinDef.DWORD(0x800F)

val OBJID_WINDOW = WinDef.LONG(0)

const val WS_EX_DLGMODALFRAME    = 0x1
const val WS_EX_NOPARENTNOTIFY   = 0x4
const val WS_EX_TOPMOST          = 0x8
const val WS_EX_ACCEPTFILES      = 0x10
const val WS_EX_TRANSPARENT      = 0x20
const val WS_EX_MDICHILD         = 0x40
const val WS_EX_TOOLWINDOW       = 0x80
const val WS_EX_WINDOWEDGE       = 0x100
const val WS_EX_CLIENTEDGE       = 0x200
const val WS_EX_CONTEXTHELP      = 0x400
const val WS_EX_RIGHT            = 0x1000
const val WS_EX_LEFT             = 0x0
const val WS_EX_RTLREADING       = 0x2000
const val WS_EX_LTRREADING       = 0x0
const val WS_EX_LEFTSCROLLBAR    = 0x4000
const val WS_EX_RIGHTSCROLLBAR   = 0x0
const val WS_EX_CONTROLPARENT    = 0x10000
const val WS_EX_STATICEDGE       = 0x20000
const val WS_EX_APPWINDOW        = 0x40000
const val WS_EX_OVERLAPPEDWINDOW = WS_EX_WINDOWEDGE or WS_EX_CLIENTEDGE
const val WS_EX_PALETTEWINDOW    = WS_EX_WINDOWEDGE or WS_EX_TOOLWINDOW or WS_EX_TOPMOST
const val WS_EX_LAYERED          = 0x80000
const val WS_EX_NOINHERITLAYOUT  = 0x100000
const val WS_EX_LAYOUTRTL        = 0x400000
const val WS_EX_COMPOSITED       = 0x2000000
const val WS_EX_NOACTIVATE       = 0x8000000